"""drop_events_redirect_token

Revision ID: 3cfb6294d09c
Revises: m6n7o8p9q0r1
Create Date: 2026-02-23 20:21:56.358494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cfb6294d09c'
down_revision: Union[str, None] = 'm6n7o8p9q0r1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_redirect_token_key', 'events', type_='unique')
    op.drop_column('events', 'redirect_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('redirect_token', sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint('events_redirect_token_key', 'events', ['redirect_token'])
    # ### end Alembic commands ###
