"""add unique constraint user_id provider on sso_accounts

Revision ID: 3d0d9985f730
Revises: 0d40bf3eaa52
Create Date: 2026-02-20 15:46:34.445816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d0d9985f730'
down_revision: Union[str, None] = '0d40bf3eaa52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_sso_user_provider', 'sso_accounts', ['user_id', 'provider'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_sso_user_provider', 'sso_accounts', type_='unique')
    # ### end Alembic commands ###
