"""add_email_verification_to_users

Revision ID: 586c7bdd872d
Revises: 11353c6cc0cb
Create Date: 2026-02-20 17:38:53.557691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '586c7bdd872d'
down_revision: Union[str, None] = '11353c6cc0cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('verification_code_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_code_expires', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('verification_code_sent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verification_code_sent_at')
    op.drop_column('users', 'verification_code_expires')
    op.drop_column('users', 'verification_code_hash')
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
