from ..feature_registry import FeatureManifest

manifest = FeatureManifest(
    name="rgpd",
    label="RGPD & Conformite",
    description="Gestion de la conformite RGPD : consentement, droits, export, pages legales, audit",
    children=[
        "rgpd.consentement",
        "rgpd.registre",
        "rgpd.droits",
        "rgpd.export",
        "rgpd.politique",
        "rgpd.audit",
    ],
    permissions=[
        "rgpd.read",
        "rgpd.consentement.read",
        "rgpd.consentement.manage",
        "rgpd.registre.read",
        "rgpd.registre.manage",
        "rgpd.droits.read",
        "rgpd.droits.manage",
        "rgpd.export.read",
        "rgpd.politique.read",
        "rgpd.politique.manage",
        "rgpd.audit.read",
    ],
    events=[
        {
            "event_type": "rgpd.consent_updated",
            "label": "Consentement mis a jour",
            "category": "RGPD",
            "description": "Un utilisateur a mis a jour ses preferences de consentement",
        },
        {
            "event_type": "rgpd.rights_request_created",
            "label": "Demande de droits creee",
            "category": "RGPD",
            "description": "Un utilisateur a soumis une demande d'exercice de droits",
        },
        {
            "event_type": "rgpd.rights_request_processed",
            "label": "Demande de droits traitee",
            "category": "RGPD",
            "description": "Un administrateur a traite une demande d'exercice de droits",
        },
        {
            "event_type": "rgpd.data_exported",
            "label": "Donnees exportees",
            "category": "RGPD",
            "description": "Un utilisateur a exporte ses donnees personnelles",
        },
        {
            "event_type": "rgpd.register_created",
            "label": "Traitement cree",
            "category": "RGPD",
            "description": "Un administrateur a ajoute une entree au registre des traitements",
        },
        {
            "event_type": "rgpd.register_updated",
            "label": "Traitement modifie",
            "category": "RGPD",
            "description": "Un administrateur a modifie une entree du registre des traitements",
        },
        {
            "event_type": "rgpd.register_deleted",
            "label": "Traitement supprime",
            "category": "RGPD",
            "description": "Un administrateur a supprime une entree du registre des traitements",
        },
        {
            "event_type": "rgpd.politique.updated",
            "label": "Page legale modifiee",
            "category": "RGPD",
            "description": "Un administrateur a modifie une page legale",
        },
        {
            "event_type": "rgpd.politique.accepted",
            "label": "Pages legales acceptees",
            "category": "RGPD",
            "description": "Un utilisateur a accepte les documents legaux",
        },
    ],
    tutorials=[
        {
            "permission": "rgpd.read",
            "label": "Vos donnees personnelles",
            "description": "Decouvrez comment consulter, exporter et supprimer vos donnees.",
            "steps": [
                {"target": ".rgpd-data-sections", "title": "Apercu de vos donnees", "description": "Visualisez toutes les donnees personnelles collectees, organisees par categorie.", "position": "top", "navigateTo": "/rgpd/my-data"},
                {"target": ".rgpd-consent-list", "title": "Preferences de consentement", "description": "Activez ou desactivez chaque type de cookies et traceurs. Les cookies necessaires ne peuvent pas etre desactives.", "position": "top", "navigateTo": "/rgpd/consent"},
                {"target": ".rgpd-rights-cta", "title": "Exercer vos droits", "description": "Soumettez une demande d'acces, de rectification, de suppression ou de portabilite de vos donnees.", "position": "top", "navigateTo": "/rgpd/my-data"},
            ],
        },
        {
            "permission": "rgpd.consentement.read",
            "label": "Gerer le consentement cookies",
            "description": "Configurez vos preferences de cookies et traceurs.",
            "steps": [{"target": ".rgpd-consent-list", "title": "Consentement", "description": "Activez ou desactivez chaque categorie de cookies et traceurs selon vos preferences.", "position": "top", "navigateTo": "/rgpd/consent"}],
        },
        {
            "permission": "rgpd.export.read",
            "label": "Exporter vos donnees",
            "description": "Telechargez une copie de vos donnees personnelles.",
            "steps": [{"target": ".rgpd-export-buttons", "title": "Export de donnees", "description": "Exportez vos donnees personnelles au format CSV ou JSON.", "position": "bottom", "navigateTo": "/rgpd/my-data"}],
        },
        {
            "permission": "rgpd.droits.read",
            "label": "Exercer vos droits",
            "description": "Soumettez une demande d'exercice de vos droits RGPD.",
            "steps": [{"target": ".rgpd-rights-cta", "title": "Demande de droits", "description": "Soumettez une demande d'acces, de rectification, d'effacement ou de portabilite de vos donnees.", "position": "top", "navigateTo": "/rgpd/my-data"}],
        },
        {
            "permission": "rgpd.registre.read",
            "label": "Administration RGPD",
            "description": "Gerez le registre des traitements, les demandes de droits et les pages legales.",
            "steps": [{"target": ".rgpd-tabs", "title": "Onglets d'administration", "description": "Naviguez entre le registre des traitements, les demandes de droits, l'audit et les pages legales.", "position": "bottom", "navigateTo": "/admin/rgpd?tab=registre"}],
        },
        {
            "permission": "rgpd.consentement.manage",
            "label": "Administrer les consentements",
            "description": "Gerez les configurations de consentement de la plateforme.",
            "steps": [{"target": ".rgpd-tabs", "title": "Administration des consentements", "description": "Configurez les categories de consentement et suivez les statistiques d'acceptation.", "position": "bottom", "navigateTo": "/admin/rgpd?tab=registre"}],
        },
        {
            "permission": "rgpd.droits.manage",
            "label": "Traiter les demandes de droits",
            "description": "Repondez aux demandes d'exercice de droits des utilisateurs.",
            "steps": [{"target": ".rgpd-tabs", "title": "Demandes de droits", "description": "Consultez les demandes en attente et traitez-les : acceptation, refus ou mise en cours. Cliquez sur \"Traiter\" pour repondre.", "position": "bottom", "navigateTo": "/admin/rgpd?tab=droits"}],
        },
        {
            "permission": "rgpd.politique.manage",
            "label": "Editer les pages legales",
            "description": "Modifiez le contenu des pages legales de la plateforme.",
            "steps": [{"target": ".rgpd-legal-list", "title": "Pages legales", "description": "Editez les pages legales : politique de confidentialite, CGU, mentions legales. Cliquez sur \"Editer\" pour modifier le contenu.", "position": "top", "navigateTo": "/admin/rgpd?tab=pages"}],
        },
        {
            "permission": "rgpd.audit.read",
            "label": "Consulter l'audit RGPD",
            "description": "Consultez le journal des acces aux donnees personnelles.",
            "steps": [{"target": ".rgpd-audit-table", "title": "Journal d'audit", "description": "Suivez les acces aux donnees personnelles : qui, quand, quelle action et sur quelle ressource.", "position": "top", "navigateTo": "/admin/rgpd?tab=audit"}],
        },
        {
            "permission": "rgpd.registre.manage",
            "label": "Gerer le registre",
            "description": "Ajoutez, modifiez et supprimez les traitements du registre RGPD.",
            "steps": [{"target": ".rgpd-section-header", "title": "Gestion du registre", "description": "Cliquez sur \"Ajouter un traitement\" pour creer une nouvelle entree au registre Article 30.", "position": "bottom", "navigateTo": "/admin/rgpd?tab=registre"}],
        },
    ],
    extra_routers=[
        {"module": "src.core.rgpd.routes_consent", "prefix": "/api/rgpd/consent", "tags": ["RGPD - Consentement"]},
        {"module": "src.core.rgpd.routes_registre", "prefix": "/api/rgpd/register", "tags": ["RGPD - Registre"]},
        {"module": "src.core.rgpd.routes_droits", "prefix": "/api/rgpd/rights", "tags": ["RGPD - Droits"]},
        {"module": "src.core.rgpd.routes_export", "prefix": "/api/rgpd/export", "tags": ["RGPD - Export"]},
        {"module": "src.core.rgpd.routes_politique", "prefix": "/api/rgpd/legal", "tags": ["RGPD - Pages legales"]},
        {"module": "src.core.rgpd.routes_audit", "prefix": "/api/rgpd/audit", "tags": ["RGPD - Audit"]},
    ],
)
