from ..feature_registry import FeatureManifest

manifest = FeatureManifest(
    name="rgpd",
    label="RGPD & Conformite",
    description="Gestion de la conformite RGPD : consentement, droits, export, pages legales, audit",
    children=[
        "rgpd.consentement",
        "rgpd.registre",
        "rgpd.droits",
        "rgpd.export",
        "rgpd.politique",
        "rgpd.audit",
    ],
    permissions=[
        "rgpd.read",
        "rgpd.consentement.read",
        "rgpd.consentement.manage",
        "rgpd.registre.read",
        "rgpd.registre.manage",
        "rgpd.droits.read",
        "rgpd.droits.manage",
        "rgpd.export.read",
        "rgpd.politique.read",
        "rgpd.politique.manage",
        "rgpd.audit.read",
    ],
    events=[
        {
            "event_type": "rgpd.consent_updated",
            "label": "Consentement mis a jour",
            "category": "RGPD",
            "description": "Un utilisateur a mis a jour ses preferences de consentement",
        },
        {
            "event_type": "rgpd.rights_request_created",
            "label": "Demande de droits creee",
            "category": "RGPD",
            "description": "Un utilisateur a soumis une demande d'exercice de droits",
        },
        {
            "event_type": "rgpd.rights_request_processed",
            "label": "Demande de droits traitee",
            "category": "RGPD",
            "description": "Un administrateur a traite une demande d'exercice de droits",
        },
        {
            "event_type": "rgpd.data_exported",
            "label": "Donnees exportees",
            "category": "RGPD",
            "description": "Un utilisateur a exporte ses donnees personnelles",
        },
        {
            "event_type": "rgpd.register_created",
            "label": "Traitement cree",
            "category": "RGPD",
            "description": "Un administrateur a ajoute une entree au registre des traitements",
        },
        {
            "event_type": "rgpd.register_updated",
            "label": "Traitement modifie",
            "category": "RGPD",
            "description": "Un administrateur a modifie une entree du registre des traitements",
        },
        {
            "event_type": "rgpd.register_deleted",
            "label": "Traitement supprime",
            "category": "RGPD",
            "description": "Un administrateur a supprime une entree du registre des traitements",
        },
        {
            "event_type": "rgpd.politique.updated",
            "label": "Page legale modifiee",
            "category": "RGPD",
            "description": "Un administrateur a modifie une page legale",
        },
        {
            "event_type": "rgpd.politique.accepted",
            "label": "Pages legales acceptees",
            "category": "RGPD",
            "description": "Un utilisateur a accepte les documents legaux",
        },
    ],
    tutorials=[
        {
            "permission": "rgpd.read",
            "label": "Vos donnees personnelles",
            "description": "Decouvrez comment consulter, exporter et supprimer vos donnees.",
            "steps": [
                {"target": ".rgpd-data-sections", "title": "Apercu de vos donnees", "description": "Visualisez toutes les donnees personnelles collectees, organisees par categorie.", "position": "top", "navigateTo": "/rgpd/my-data"},
                {"target": ".rgpd-consent-list", "title": "Preferences de consentement", "description": "Activez ou desactivez chaque type de cookies et traceurs. Les cookies necessaires ne peuvent pas etre desactives.", "position": "top", "navigateTo": "/rgpd/consent"},
                {"target": ".rgpd-rights-cta", "title": "Exercer vos droits", "description": "Soumettez une demande d'acces, de rectification, de suppression ou de portabilite de vos donnees.", "position": "top", "navigateTo": "/rgpd/my-data"},
            ],
        },
    ],
    tutorial_order=40,
    extra_routers=[
        {"module": "src.core.rgpd.routes_consent", "prefix": "/api/rgpd/consent", "tags": ["RGPD - Consentement"]},
        {"module": "src.core.rgpd.routes_registre", "prefix": "/api/rgpd/register", "tags": ["RGPD - Registre"]},
        {"module": "src.core.rgpd.routes_droits", "prefix": "/api/rgpd/rights", "tags": ["RGPD - Droits"]},
        {"module": "src.core.rgpd.routes_export", "prefix": "/api/rgpd/export", "tags": ["RGPD - Export"]},
        {"module": "src.core.rgpd.routes_politique", "prefix": "/api/rgpd/legal", "tags": ["RGPD - Pages legales"]},
        {"module": "src.core.rgpd.routes_audit", "prefix": "/api/rgpd/audit", "tags": ["RGPD - Audit"]},
    ],
)
