"""RGPD business logic — user data collection for export."""

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession


async def collect_user_data(db: AsyncSession, user_id: int) -> dict:
    """Collect all personal data stored about a user, grouped by section."""
    from .._identity.models import User, UserPermission, UserRole, UserSession
    from ..event.models import Event
    from ..notification.models import Notification, NotificationRule, UserRulePreference
    from .models import ConsentRecord, RightsRequest

    data = {}

    # --- Profile ---
    result = await db.execute(select(User).where(User.id == user_id))
    user = result.scalar_one_or_none()
    if user:
        data["profil"] = {
            "id": user.id,
            "email": user.email,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "auth_source": user.auth_source,
            "email_verified": user.email_verified,
            "is_active": user.is_active,
            "preferences": user.preferences or {},
            "last_login": str(user.last_login) if user.last_login else None,
            "last_active": str(user.last_active) if user.last_active else None,
            "created_at": str(user.created_at),
        }

    # --- Roles ---
    result = await db.execute(
        select(UserRole).where(UserRole.user_id == user_id)
    )
    roles = result.scalars().all()
    if roles:
        data["roles"] = [{"role_id": r.role_id} for r in roles]

    # --- Direct permissions ---
    result = await db.execute(
        select(UserPermission).where(UserPermission.user_id == user_id)
    )
    perms = result.scalars().all()
    if perms:
        data["permissions_directes"] = [
            {"permission_id": p.permission_id, "granted": p.granted} for p in perms
        ]

    # --- Sessions ---
    result = await db.execute(
        select(UserSession).where(UserSession.user_id == user_id)
    )
    sessions = result.scalars().all()
    if sessions:
        data["sessions"] = [
            {
                "ip_address": s.ip_address,
                "user_agent": s.user_agent,
                "is_revoked": s.is_revoked,
                "created_at": str(s.created_at),
                "expires_at": str(s.expires_at),
            }
            for s in sessions
        ]

    # --- Notifications ---
    result = await db.execute(
        select(Notification)
        .where(Notification.user_id == user_id, Notification.deleted_at.is_(None))
        .order_by(Notification.created_at.desc())
        .limit(100)
    )
    notifs = result.scalars().all()
    if notifs:
        data["notifications"] = [
            {
                "id": n.id,
                "title": n.title,
                "body": n.body,
                "is_read": n.is_read,
                "created_at": str(n.created_at),
            }
            for n in notifs
        ]

    # --- Notification rules created by user ---
    result = await db.execute(
        select(NotificationRule).where(NotificationRule.created_by_id == user_id)
    )
    rules = result.scalars().all()
    if rules:
        data["regles_notification"] = [
            {"id": r.id, "name": r.name, "event_types": r.event_types, "is_active": r.is_active}
            for r in rules
        ]

    # --- User rule preferences ---
    result = await db.execute(
        select(UserRulePreference).where(UserRulePreference.user_id == user_id)
    )
    prefs = result.scalars().all()
    if prefs:
        data["preferences_regles"] = [
            {"rule_id": p.rule_id, "is_active": p.is_active} for p in prefs
        ]

    # --- Events generated by user ---
    result = await db.execute(
        select(Event)
        .where(Event.actor_id == user_id)
        .order_by(Event.created_at.desc())
        .limit(200)
    )
    events = result.scalars().all()
    if events:
        data["evenements"] = [
            {
                "event_type": e.event_type,
                "resource_type": e.resource_type,
                "resource_id": e.resource_id,
                "created_at": str(e.created_at),
            }
            for e in events
        ]

    # --- Consent records ---
    result = await db.execute(
        select(ConsentRecord)
        .where(ConsentRecord.user_id == user_id)
        .order_by(ConsentRecord.created_at.desc())
    )
    consents = result.scalars().all()
    if consents:
        data["consentements"] = [
            {
                "type": c.consent_type,
                "granted": c.granted,
                "ip_address": c.ip_address,
                "created_at": str(c.created_at),
            }
            for c in consents
        ]

    # --- Rights requests ---
    result = await db.execute(
        select(RightsRequest)
        .where(RightsRequest.user_id == user_id)
        .order_by(RightsRequest.created_at.desc())
    )
    requests = result.scalars().all()
    if requests:
        data["demandes_droits"] = [
            {
                "type": r.request_type,
                "status": r.status,
                "description": r.description,
                "admin_response": r.admin_response,
                "created_at": str(r.created_at),
                "completed_at": str(r.completed_at) if r.completed_at else None,
            }
            for r in requests
        ]

    return data
