services:
  api:
    volumes:
      - ./api/src:/app/src
      - ./api/alembic:/app/alembic
      - ./backups:/app/backups

  worker:
    volumes:
      - ./api/src:/app/src

  app:
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - ./app/index.html:/app/index.html
      - ./app/vite.config.ts:/app/vite.config.ts
      - ./app/package.json:/app/package.json
