from ..feature_registry import FeatureManifest
from .middleware import ImpersonationAuditMiddleware, LastActiveMiddleware

manifest = FeatureManifest(
    name="_identity",
    label="Identity",
    description="Authentication, users, roles, permissions, feature management",
    version="2026.02.17",
    is_core=True,
    permissions=[
        "users.read", "users.create", "users.update", "users.delete",
        "roles.read", "roles.create", "roles.update", "roles.delete",
        "permissions.read", "permissions.manage",
        "features.read", "features.manage",
        "settings.read", "settings.manage",
        "invitations.create", "invitations.read",
        "impersonation.start", "impersonation.read",
        "backups.create", "backups.restore", "backups.read",
        "search.global",
        "commands.read", "commands.manage",
    ],
    events=[
        {"event_type": "user.registered", "label": "Utilisateur inscrit", "category": "Utilisateurs", "description": "Un nouvel utilisateur s'est inscrit"},
        {"event_type": "user.invited", "label": "Utilisateur invite", "category": "Utilisateurs", "description": "Un utilisateur a ete invite"},
        {"event_type": "user.invitation_accepted", "label": "Invitation acceptee", "category": "Utilisateurs", "description": "Un utilisateur invite a accepte l'invitation"},
        {"event_type": "user.updated", "label": "Profil mis a jour", "category": "Utilisateurs", "description": "Un utilisateur a mis a jour son profil"},
        {"event_type": "user.deactivated", "label": "Utilisateur desactive", "category": "Utilisateurs", "description": "Un utilisateur a ete desactive"},
        {"event_type": "admin.impersonation_started", "label": "Impersonation demarree", "category": "Administration", "description": "Un administrateur impersonifie un utilisateur", "admin_only": True},
    ],
    middleware=[ImpersonationAuditMiddleware, LastActiveMiddleware],
    extra_routers=[
        {"module": "src.core._identity.routes_auth", "prefix": "/api/auth", "tags": ["Auth"]},
        {"module": "src.core._identity.routes_users", "prefix": "/api/users", "tags": ["Users"]},
        {"module": "src.core._identity.routes_roles", "prefix": "/api/roles", "tags": ["Roles"]},
        {"module": "src.core._identity.routes_permissions", "prefix": "/api/permissions", "tags": ["Permissions"]},
        {"module": "src.core._identity.routes_features", "prefix": "/api/features", "tags": ["Features"]},
        {"module": "src.core._identity.routes_settings", "prefix": "/api/settings", "tags": ["Settings"]},
        {"module": "src.core._identity.routes_health", "prefix": "/api", "tags": ["Health"]},
        {"module": "src.core._identity.routes_search", "prefix": "/api", "tags": ["Search"]},
        {"module": "src.core._identity.routes_impersonation", "prefix": "/api/impersonation", "tags": ["Impersonation"]},
        {"module": "src.core._identity.routes_invitations", "prefix": "/api", "tags": ["Invitations"]},
        {"module": "src.core._identity.routes_backups", "prefix": "/api/backups", "tags": ["Backups"]},
        {"module": "src.core._identity.routes_commands", "prefix": "/api/commands", "tags": ["Commands"]},
    ],
)
