from ..feature_registry import FeatureManifest
from .middleware import ImpersonationAuditMiddleware, LastActiveMiddleware

manifest = FeatureManifest(
    name="_identity",
    label="Identity",
    description="Authentication, users, roles, permissions, feature management",
    is_core=True,
    permissions=[
        "users.read", "users.create", "users.update", "users.delete",
        "roles.read", "roles.create", "roles.update", "roles.delete", "roles.assign_super_admin",
        "permissions.read", "permissions.manage",
        "features.read", "features.manage",
        "settings.read", "settings.manage",
        "invitations.create", "invitations.read", "invitations.delete",
        "impersonation.start", "impersonation.read", "impersonation.immune",
        "backups.create", "backups.restore", "backups.read",
        "search.global",
        "commands.read", "commands.manage",
    ],
    events=[
        # Authentification
        {"event_type": "user.login", "label": "Connexion", "category": "Authentification", "description": "Un utilisateur s'est connecte"},
        {"event_type": "user.password_changed", "label": "Mot de passe modifie", "category": "Authentification", "description": "Un utilisateur a modifie son mot de passe"},
        {"event_type": "user.password_reset", "label": "Mot de passe reinitialise", "category": "Authentification", "description": "Un mot de passe a ete reinitialise via token"},
        {"event_type": "user.email_verified", "label": "Email verifie", "category": "Authentification", "description": "Un utilisateur a verifie son adresse email"},
        # Utilisateurs
        {"event_type": "user.registered", "label": "Utilisateur inscrit", "category": "Utilisateurs", "description": "Un nouvel utilisateur s'est inscrit"},
        {"event_type": "user.invited", "label": "Utilisateur invite", "category": "Utilisateurs", "description": "Un utilisateur a ete invite"},
        {"event_type": "user.invitation_accepted", "label": "Invitation acceptee", "category": "Utilisateurs", "description": "Un utilisateur invite a accepte l'invitation"},
        {"event_type": "user.updated", "label": "Profil mis a jour", "category": "Utilisateurs", "description": "Un utilisateur a mis a jour son profil"},
        {"event_type": "user.deactivated", "label": "Utilisateur desactive", "category": "Utilisateurs", "description": "Un utilisateur a ete desactive"},
        {"event_type": "user.deleted", "label": "Utilisateur supprime", "category": "Utilisateurs", "description": "Un compte utilisateur a ete supprime"},
        {"event_type": "user.account_deleted", "label": "Compte auto-supprime", "category": "Utilisateurs", "description": "Un utilisateur a supprime son propre compte"},
        {"event_type": "user.roles_updated", "label": "Roles modifies", "category": "Utilisateurs", "description": "Les roles d'un utilisateur ont ete modifies"},
        # Roles
        {"event_type": "role.created", "label": "Role cree", "category": "Roles", "description": "Un nouveau role a ete cree"},
        {"event_type": "role.updated", "label": "Role modifie", "category": "Roles", "description": "Un role a ete modifie"},
        {"event_type": "role.deleted", "label": "Role supprime", "category": "Roles", "description": "Un role a ete supprime"},
        {"event_type": "role.permissions_updated", "label": "Permissions du role modifiees", "category": "Roles", "description": "Les permissions d'un role ont ete modifiees"},
        # Administration
        {"event_type": "admin.impersonation_started", "label": "Impersonation demarree", "category": "Administration", "description": "Un administrateur impersonifie un utilisateur"},
        {"event_type": "admin.impersonation_stopped", "label": "Impersonation terminee", "category": "Administration", "description": "Une session d'impersonation a ete terminee"},
        {"event_type": "admin.password_reset_triggered", "label": "Reset password declenche", "category": "Administration", "description": "Un admin a declenche la reinitialisation du mot de passe d'un utilisateur"},
        {"event_type": "admin.global_permissions_updated", "label": "Permissions globales modifiees", "category": "Administration", "description": "Les permissions globales ont ete modifiees"},
        {"event_type": "admin.feature_toggled", "label": "Feature activee/desactivee", "category": "Administration", "description": "Une feature a ete activee ou desactivee"},
        {"event_type": "admin.settings_updated", "label": "Parametres modifies", "category": "Administration", "description": "Les parametres de l'application ont ete modifies"},
        # Commandes
        {"event_type": "command.executed", "label": "Commande executee", "category": "Administration", "description": "Une commande de maintenance a ete executee"},
        {"event_type": "command.toggled", "label": "Commande activee/desactivee", "category": "Administration", "description": "Une commande a ete activee ou desactivee"},
        # Preferences
        {"event_type": "preference.updated", "label": "Preferences modifiees", "category": "Utilisateurs", "description": "Un utilisateur a modifie ses preferences"},
    ],
    tutorials=[
        {
            "permission": "search.global",
            "label": "Recherche globale",
            "description": "Trouvez rapidement utilisateurs, roles et parametres depuis la barre de recherche.",
            "steps": [{"target": ".global-search-container", "title": "Recherche globale", "description": "Utilisez cette barre de recherche pour trouver rapidement des utilisateurs, roles ou parametres.", "position": "bottom"}],
        },
        {
            "permission": "users.read",
            "label": "Consulter les utilisateurs",
            "description": "Consultez la liste des utilisateurs, leur statut et leur derniere connexion.",
            "steps": [
                {"target": ".unified-search-box", "title": "Recherche d'utilisateurs", "description": "Filtrez la liste des utilisateurs par email, nom ou prenom.", "position": "bottom", "navigateTo": "/admin/users?tab=users"},
                {"target": ".unified-table", "title": "Liste des utilisateurs", "description": "Consultez tous les utilisateurs, leur statut et leur derniere connexion. Cliquez sur un utilisateur pour voir ses details.", "position": "top", "navigateTo": "/admin/users?tab=users"},
            ],
        },
        {
            "permission": "users.create",
            "label": "Creer un utilisateur",
            "description": "Ajoutez de nouveaux utilisateurs au systeme.",
            "steps": [{"target": ".btn-unified-primary", "title": "Creer un utilisateur", "description": "Cliquez ici pour ajouter un nouvel utilisateur au systeme.", "position": "bottom", "navigateTo": "/admin/users?tab=users"}],
        },
        {
            "permission": "roles.read",
            "label": "Consulter les roles",
            "description": "Consultez les roles existants et leurs permissions associees.",
            "steps": [{"target": ".unified-table", "title": "Liste des roles", "description": "Consultez les roles existants et leurs permissions associees. Cliquez sur le badge de permissions pour voir les details.", "position": "top", "navigateTo": "/admin/roles"}],
        },
        {
            "permission": "roles.create",
            "label": "Creer un role",
            "description": "Creez de nouveaux roles avec des permissions personnalisees.",
            "steps": [{"target": ".btn-unified-primary", "title": "Creer un role", "description": "Cliquez ici pour creer un nouveau role avec des permissions personnalisees.", "position": "bottom", "navigateTo": "/admin/roles"}],
        },
        {
            "permission": "features.read",
            "label": "Gerer les features",
            "description": "Activez ou desactivez les modules de l'application.",
            "steps": [
                {"target": ".input-search-wide", "title": "Recherche de features", "description": "Recherchez des features par nom ou description.", "position": "bottom", "navigateTo": "/admin/features"},
                {"target": ".unified-table", "title": "Liste des features", "description": "Activez ou desactivez les features avec les toggles. Les features enfants dependent de leur parent.", "position": "top", "navigateTo": "/admin/features"},
            ],
        },
        {
            "permission": "settings.read",
            "label": "Parametres applicatifs",
            "description": "Configurez le nom, la description, le logo et les couleurs de l'application.",
            "steps": [{"target": ".settings-grid", "title": "Parametres de l'application", "description": "Configurez le nom, la description, le logo et les couleurs de votre application.", "position": "top", "navigateTo": "/admin/settings"}],
        },
        {
            "permission": "impersonation.start",
            "label": "Impersonation",
            "description": "Connectez-vous en tant qu'un autre utilisateur pour diagnostiquer des problemes.",
            "steps": [{"target": ".impersonate-btn", "title": "Impersonation", "description": "Cliquez sur ce bouton pour vous connecter en tant que cet utilisateur. Utile pour diagnostiquer des problemes.", "position": "left", "navigateTo": "/admin/users"}],
        },
        {
            "permission": "users.update",
            "label": "Modifier un utilisateur",
            "description": "Modifiez les informations, roles et permissions d'un utilisateur.",
            "steps": [{"target": ".unified-table tbody tr", "title": "Details utilisateur", "description": "Cliquez sur un utilisateur pour acceder a sa fiche et modifier ses informations, roles ou permissions.", "position": "top", "navigateTo": "/admin/users"}],
        },
        {
            "permission": "users.delete",
            "label": "Supprimer un utilisateur",
            "description": "Supprimez un utilisateur du systeme.",
            "steps": [{"target": ".btn-icon-danger", "title": "Supprimer", "description": "Cliquez sur l'icone de suppression pour retirer un utilisateur. Cette action est irreversible.", "position": "left", "navigateTo": "/admin/users"}],
        },
        {
            "permission": "roles.update",
            "label": "Modifier un role",
            "description": "Modifiez le nom, la description ou les permissions d'un role existant.",
            "steps": [{"target": ".unified-table", "title": "Modifier un role", "description": "Utilisez les icones de modification dans le tableau pour editer le nom, la description et les permissions d'un role.", "position": "top", "navigateTo": "/admin/roles"}],
        },
        {
            "permission": "roles.delete",
            "label": "Supprimer un role",
            "description": "Supprimez un role qui n'est plus necessaire.",
            "steps": [{"target": ".unified-table", "title": "Supprimer un role", "description": "Utilisez l'icone de suppression dans le tableau pour retirer un role. Les utilisateurs associes perdront ses permissions.", "position": "top", "navigateTo": "/admin/roles"}],
        },
        {
            "permission": "permissions.read",
            "label": "Consulter les permissions",
            "description": "Consultez la liste des permissions disponibles et leur etat.",
            "steps": [{"target": ".unified-table", "title": "Liste des permissions", "description": "Consultez toutes les permissions du systeme, groupees par feature. Chaque permission peut etre activee ou desactivee.", "position": "top", "navigateTo": "/admin/permissions"}],
        },
        {
            "permission": "permissions.manage",
            "label": "Gerer les permissions",
            "description": "Activez ou desactivez les permissions et configurez les acces.",
            "steps": [{"target": ".toggle-switch", "title": "Activer/desactiver", "description": "Utilisez les toggles pour activer ou desactiver des permissions individuelles.", "position": "left", "navigateTo": "/admin/permissions"}],
        },
        {
            "permission": "invitations.read",
            "label": "Consulter les invitations",
            "description": "Consultez les invitations envoyees et leur statut.",
            "steps": [{"target": ".invitations-table", "title": "Liste des invitations", "description": "Retrouvez ici toutes les invitations envoyees, leur statut (en attente, expiree) et la date d'envoi.", "position": "top", "navigateTo": "/admin/users?tab=invitations"}],
        },
        {
            "permission": "invitations.create",
            "label": "Envoyer une invitation",
            "description": "Invitez de nouveaux utilisateurs par email.",
            "steps": [{"target": ".btn-unified-primary", "title": "Inviter un utilisateur", "description": "Cliquez ici pour envoyer une invitation par email. L'utilisateur recevra un lien pour creer son compte.", "position": "bottom", "navigateTo": "/admin/users?tab=invitations"}],
        },
    ],
    middleware=[ImpersonationAuditMiddleware, LastActiveMiddleware],
    extra_routers=[
        {"module": "src.core._identity.routes_auth", "prefix": "/api/auth", "tags": ["Auth"]},
        {"module": "src.core._identity.routes_users", "prefix": "/api/users", "tags": ["Users"]},
        {"module": "src.core._identity.routes_roles", "prefix": "/api/roles", "tags": ["Roles"]},
        {"module": "src.core._identity.routes_permissions", "prefix": "/api/permissions", "tags": ["Permissions"]},
        {"module": "src.core._identity.routes_features", "prefix": "/api/features", "tags": ["Features"]},
        {"module": "src.core._identity.routes_settings", "prefix": "/api/settings", "tags": ["Settings"]},
        {"module": "src.core._identity.routes_health", "prefix": "/api", "tags": ["Health"]},
        {"module": "src.core._identity.routes_search", "prefix": "/api", "tags": ["Search"]},
        {"module": "src.core._identity.routes_impersonation", "prefix": "/api/impersonation", "tags": ["Impersonation"]},
        {"module": "src.core._identity.routes_invitations", "prefix": "/api", "tags": ["Invitations"]},
        {"module": "src.core._identity.routes_backups", "prefix": "/api/backups", "tags": ["Backups"]},
        {"module": "src.core._identity.routes_commands", "prefix": "/api/commands", "tags": ["Commands"]},
    ],
)
